languageCode = "ua-ua"
theme = "hugo-theme-dream"
title = "microdiy.space"


[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[module]
    [[module.mounts]]
    source = 'static'
    target = 'static'

    [[module.mounts]]
    source = 'images'
    target = 'static/images'
